### ISSUE TITLE
One quick question

### ISSUE THREAD

**Issue by robotaoyuan** [mapbox/weekend-picks-template-ios#4]
Hi guys,
Sorry this issue may appear irrelevant but I am quite desperate now...
![screen shot 2014-07-25 at 4 18 52 pm](https://cloud.githubusercontent.com/assets/4868985/3699476/adb3ad32-13d4-11e4-9f5b-5f9fefc2c12d.png)
Above shows the "breath light" effect in weekend-picks app when user click on the left navigation button. 

How did you guys implement this breath light effect using mapbox? Is this part of the userLocation functionalities in RMMapView or is it something specific to weekend-pick app? My guess is this is a native effect from RMMapView but I failed to locate the code that does this cool effect. Sorry for being a noob... Can you help me out???

**Comment by friedbunny** [comment]
Have a look at: https://github.com/TransitApp/SVPulsingAnnotationView
