### ISSUE TITLE
error on compiling with different mapboxIDs

### ISSUE THREAD

**Issue by miccferr** [mapbox/weekend-picks-template-ios#5]
Hey guys,
I'm really not an iOS dev, just tinkering with this template..
It works fine with the default parameters  ```kMapboxMapID``` in the ```MBWPViewController.m```  file, but if I swap my mapbox ID with the default one  it crashes. (my ID is related to a project containing just a bunch of markers, originally from a .geojson file)
Xcode builds everything, and starts the iOS simulator, but once it zooms on the area, the app simply crashes rising the following error:

````
2015-03-08 18:53:04.421 Picks[6590:182552] DB Error: 1 "near "-": syntax error"
2015-03-08 18:53:04.421 Picks[6590:182552] DB Query: PRAGMA cache-size=100
2015-03-08 18:53:04.421 Picks[6590:182552] DB Path: /Volumes/old_hdd/Utenti/mic/Library/Developer/CoreSimulator/Devices/129A0ABE-AE7C-4C6A-954B-E9C70A39D3DF/data/Containers/Data/Application/429C0604-2396-4204-8129-FD0A812F3BC9/Documents/RMTileCache.db
2015-03-08 18:53:06.292 Picks[6590:182552] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringToIndex:]: Index 1 out of bounds; string length 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107364f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106ffdbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000107364e6d +[NSException raise:format:] + 205
	3   Foundation                          0x0000000105525865 -[NSString substringToIndex:] + 118
	4   Picks                               0x000000010506dccb -[RMMarker initWithMapboxMarkerImage:tintColorHex:sizeString:] + 476
	5   Picks                               0x000000010504dac7 -[MBWPViewController mapView:layerForAnnotation:] + 455
	6   Picks                               0x0000000105066d7b -[RMMapView correctPositionOfAllAnnotationsIncludingInvisibles:animated:] + 3299
	7   Picks                               0x000000010505f951 -[RMMapView scrollViewDidEndZooming:withView:atScale:] + 118
	8   UIKit                               0x0000000105cbaaf6 -[UIScrollView _zoomAnimationDidStop] + 294
	9   UIKit                               0x0000000105c86e6a -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 209
	10  UIKit                               0x0000000105c871a0 -[UIViewAnimationState animationDidStop:finished:] + 76
	11  QuartzCore                          0x0000000105ab47ee _ZN2CA5Layer23run_animation_callbacksEPv + 308
	12  libdispatch.dylib                   0x000000010795d7f4 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00000001079468fb _dispatch_main_queue_callback_4CF + 949
	14  CoreFoundation                      0x00000001072ccfe9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x000000010728feeb __CFRunLoopRun + 2043
	16  CoreFoundation                      0x000000010728f486 CFRunLoopRunSpecific + 470
	17  GraphicsServices                    0x00000001097509f0 GSEventRunModal + 161
	18  UIKit                               0x0000000105c2d420 UIApplicationMain + 1282
	19  Picks                               0x000000010504bc53 main + 115
	20  libdyld.dylib                       0x0000000107992145 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

`````

Is it related to my file? Perhaps something with formatting?  
I've tested my original  geojson on geojson.io and geojsonlint.com and it seems fine..  
If somebody wants to check with my ID I can send it via private email.
Thanks in advance!

**Comment by friedbunny** [comment]
It looks like your GeoJSON doesn't have the [styling properties](https://www.mapbox.com/guides/an-open-platform/#simplestyle) the Weekend Picks demo app expects. You'll need to change [how the markers are added to the map](https://github.com/mapbox/weekend-picks-template-ios/blob/master/Weekend%20Picks/MBWPViewController.m#L137-L139) or add the necessary styling to your data.

Also see:
- [Example of how to draw a marker](https://www.mapbox.com/mapbox-ios-sdk/examples/marker/)
- [Marker class overview](https://www.mapbox.com/mapbox-ios-sdk/#markers__shapes__and_subclasses)
- [RMMarker class reference](https://www.mapbox.com/mapbox-ios-sdk/api/Classes/RMMarker.html)

**Comment by miccferr** [comment]
ok thanks, I was under the impression that styling properties you are referring to would have been passed from the mapbox API (since my markers are coming from that platform via my Mabìpbox ID, rather than directly from a local GeoJSON, let's say..). 
I mean, aren't [these three properties](https://github.com/mapbox/weekend-picks-template-ios/blob/master/Weekend%20Picks/MBWPViewController.m#L137-L139) already populated by the mapbox markers' values, once I create a map on the Mapbox Editor and then use that ID?

Also, if I try to use different IDs, even when there are no markers/GeoJSON involved (i.e. just a map with a plain satellite background), the app crashes raising an error akin to the [#557 #558  issues ](https://github.com/mapbox/mapbox-ios-sdk/pull/558) on mapbox-ios-sdk repo:

`````
2015-03-11 09:49:40.119 Picks[1553:38753] DB Error: 1 "near "-": syntax error"
2015-03-11 09:49:40.119 Picks[1553:38753] DB Query: PRAGMA cache-size=100
2015-03-11 09:49:40.119 Picks[1553:38753] DB Path: /Volumes/old_hdd/Utenti/mic/Library/Developer/CoreSimulator/Devices/1D8F3F06-7A54-494A-A8AC-82D6844E1B62/data/Containers/Data/Application/85FE9C55-44DB-4AC8-A054-6541B78460B0/Documents/RMTileCache.db
````   
From the looks like of the last commit the SDK library shipped within this weekend-picks-repo is 1.5.0 while now the version is 1.6.0. 
It's not too far away, but..might this be the issue?
In such case, what would be my best option to upgrade the SDK without breaking everything?
Thanks!

**Comment by friedbunny** [comment]
You're right that the map you generated should have these properties, this looks like a bug there. When I use the online editor to place markers all the properties are set, but when importing GeoJSON it doesn't force you to select the color, size, or symbol — even though it will subsequently show you a grey medium blank marker.

I'll try to get this issue with the online editor addressed, but in the meantime here's what you can do:

 1. Reimport your GeoJSON in the editor
 2. When the styling dialog pops up, make sure you select a size, color, and then also a symbol

`[RMMarker initWithMapboxMarkerImage:tintColorHex:sizeString:]` will fail silently without a symbol and crash without a size. If you don't want your markers to have any/all of those properties, the best way would be to use one of the other methods for adding markers that better fits your styling, like [`[RMMarker initWithMapboxMarkerImage:tintColor:]`](https://www.mapbox.com/mapbox-ios-sdk/api/Classes/RMMarker.html#//api/name/initWithMapboxMarkerImage:tintColor:).

`RMMarker` could definitely stand to be more resilient in the face of uncertain data.

You're also right that mapbox/mapbox-ios-sdk/pull/558 fixes the `DB Error` you noticed and that's in 1.6.0, but I don't believe that has any effect on this issue. You could try updating to 1.6.0, but that has a regression that causes crashes when trying to draw markers, mapbox/mapbox-ios-sdk/issues/590.

**Comment by miccferr** [comment]
@friedbunny I have always  styled the GeoJSON (with size/dialog/color/symbol) while importing it, but unfortunately to no avail.. :sob: 

Also, I don't get what you are suggesting by saying:

> If you don't want your markers to have any/all of those properties..

On the contrary, I want my data to be differentiated according to each marker's category :smile: 
 (I mean, isn't the whole point of this demo to be able to toggle between different categories? ) 
So when you suggest to use methods such as ``` [RMMarker initWithMapboxMarkerImage:tintColor:]```then I still want to be able to pass them different values. 
For instance the values of ```symbolName``` or ```color```should be taken from the markers, according to their  properties..

I'm truly starting to think it has simply something to do with this  error https://github.com/mapbox/mapbox-ios-sdk/pull/558, (I keep getting the  ```DB Error: 1 "near "-": syntax error" ```error log) 
Or maybe is something related to  zooming/bounding box. Because it builds and I can use it for a few seconds, but after i move the map a bit, or zoom closer to my markers' area it crashes.
Since my starting position is in the middle of nowhere, can't this be the issue? 
I mean that I'm too far away from my markers..
If so, where in the code should put my initial location/reset the bounding box to a place closer to my markers?

Thanks for you patience! :+1:

**Comment by friedbunny** [comment]
> If you don't want your markers to have any/all of those properties..

By that I meant that it would ideal to use the least complicated way to set a marker, based on your needs. If you want to be able to set every property, I'd suggest checking first to see if those properties exist:

```objective-c
NSString *markerSymbol = [annotation.userInfo objectForKey:@"marker-symbol"];
if (!markerSymbol.length) markerSymbol = nil;

NSString *markerColor = [annotation.userInfo objectForKey:@"marker-color"];
if (!markerColor.length) markerColor = @"#00F";

NSString *markerSize = [annotation.userInfo objectForKey:@"marker-size"];
if (!markerSize.length) markerSize = @"medium";

RMMarker *marker = [[RMMarker alloc] initWithMapboxMarkerImage:markerSymbol
                                                  tintColorHex:markerColor
                                                    sizeString:markerSize];
```

Those checks fix the crashing for me when using not-completely-defined symbol styles, like with Mapbox map `friedbunny.lec17m0c`.

The map doesn't crash immediately because [there's an intentional 1 second delay before the markers are drawn](https://github.com/mapbox/weekend-picks-template-ios/blob/8c071ae4b1ae1423e2eb504125678f5bdf9842f6/Weekend%20Picks/MBWPViewController.m#L74-L94).

As for the initial bounding box, you can set it in `viewDidAppear` with [`[RMMapView zoomWithLatitudeLongitudeBoundsSouthWest:northEast:animated:]`](http://cocoadocs.org/docsets/Mapbox-iOS-SDK/1.6.0/Classes/RMMapView.html#//api/name/zoomWithLatitudeLongitudeBoundsSouthWest:northEast:animated:) like this:

```objective-c
[self.mapView zoomWithLatitudeLongitudeBoundsSouthWest:CLLocationCoordinate2DMake(45.43, -122.84)
                                             northEast:CLLocationCoordinate2DMake(45.65, -122.47)
                                              animated:NO];
```

Or just center on a coordinate at a specified zoom using [`[RMMapView setZoom:atCoordinate:animated:]`](http://cocoadocs.org/docsets/Mapbox-iOS-SDK/1.6.0/Classes/RMMapView.html#//api/name/setZoom:atCoordinate:animated:):

```objective-c
[self.mapView setZoom:10.0f
         atCoordinate:CLLocationCoordinate2DMake(45.5444543, -122.6767401)
             animated:NO];
```

If you want to try updating to [1.6.0](https://mapbox-ios-sdk.s3.amazonaws.com/index.html), replace the contents of the `Mapbox` directory and clean the project (⇧⌘K). There are some issues you'll encounter with the update (see #7), though.

**Comment by miccferr** [comment]
Thanks for your detailed reply.
I'll see if I can get a hold of it in the weekend, and get back at you.
Cheers!
